[settings]
max_iter = 1000
stop_iter_lambda = 100
start_input_lambda = 2
start_undriven_lambda = 2
prob_sequential = 0

[priorities]
AddRandomModule = 20
AddExternalNet = 5
AddUndriveNet = 10
DriveUndrivenNet = 15
DriveUndrivenNets = 0
SwitchUp = 0
BufferUnconnectedOutputs = 0