[settings]
max_iter = 1000
stop_iter_lamba = 20
starting_input_nets_lamba = 2
starting_undriven_nets_lamba = 2
prob_sequential = 0.1

[priorities]
AddRandomModule = 20
AddExternalNet = 5
AddUndriveNet = 10
DriveUndrivenNet = 15
DriveUndrivenNets = 0
SwitchUp = 0
BufferUnconnectedOutputs = 0