name: Build & Release Fuznet

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential \
            libyaml-cpp-dev

      - name: Configure & build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)

      - name: Strip & package
        run: |
          cd build
          strip fuznet
          tar czf fuznet-${{ github.ref_name }}-linux.tar.gz fuznet

      - name: Create GitHub Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}

      - name: Upload binary artifact
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: build/fuznet-${{ github.ref_name }}-linux.tar.gz
          asset_name: fuznet-${{ github.ref_name }}-linux.tar.gz
          asset_content_type: application/gzip